version: '3'
services:
  postgres:
    container_name: 'ead-authuser'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5433:5432'