version: '3'
services:
  postgres:
    container_name: 'projeto-decoder'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'